### ISSUE TITLE
Enhancement: Switch to using Docusaurus

### ISSUE THREAD

**Issue by ProfDavidRoberts** [opendi-org/landing-site#3]
## Is your enhancement request related to a problem or unique use case? If so, please describe.
As we move forward in revising the drafts to become standards, which presumably will go through iterations and ratification over the coming years, it will be important to be able to 1) review a current, unratified, draft as well as 2) refer back to specific versions of standards that were ratified at earlier points in time. The current toolchain (MKDocs) doesn't support this functionality. 

## Describe the enhancement
[Docusaurus](https://docusaurus.io) provides a natural way to manage versioning and review of live edits on various git branches. We should refactor the GitHub workflow to leverage the Docusaurus tool. 

## Describe alternatives you've considered
I was involved in the initial discussion that selected MKDocs, where we considered a number of alternatives (e.g., readthedocs, etc.). Having spoken with someone involved in another community standard, there was as strong recommendation to adopt Docusaurs. 

## Additional context
N/A.

**Comment by ProfDavidRoberts** [comment]
FYI, this issue would apply to other OpenDI repositories as well. (Roles and User Stories, JSON Schema, etc.).

**Comment by isaac-kellogg-quantellia** [comment]
Closed by [5984212](https://github.com/opendi-org/json-schema/commit/5984212c249af29f8945567ac27d222b1ceefcac), [f2edcca](https://github.com/opendi-org/roles-user-stories/commit/f2edccac099adc1e83458b32904594d2f204e760), and [131c002](https://github.com/opendi-org/landing-site/commit/131c002b49f30cea229089e250bc6e12b82ffc52).

New deployment for each repo can be seen at
- https://opendi.org/
- http://roles-user-stories.opendi.org/
- http://json-schema.opendi.org/
